# .github/workflows/deploy.yml

# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: Deploy to VPS

# Disparador: Este workflow se ejecuta cada vez que hacés un push a la rama 'main'
on:
  push:
    branches: [ main ]

# Trabajos: Definimos un único trabajo llamado 'deploy'
jobs:
  deploy:
    # La máquina virtual que usará GitHub para correr este trabajo
    runs-on: ubuntu-latest

    # Pasos que se ejecutarán en secuencia
    steps:
      - name: Deploy to VPS via SSH
        # Usamos una Action popular de la comunidad para conectarnos por SSH y ejecutar comandos
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Definimos las rutas de los proyectos para más claridad
            export DEPLOY_DIR=~/instituto-deployment
            export FRONTEND_DIR=~/instituto-asistencias-front
            export BACKEND_DIR=~/InstitutoAdv.API

            # --- Setup/Update Deployment Repo ---
            if [ -d "$DEPLOY_DIR" ]; then
              echo ">>> Actualizando repositorio de despliegue..."
              cd $DEPLOY_DIR && git pull
            else
              echo ">>> Clonando repositorio de despliegue..."
              git clone git@github.com:tu-usuario/instituto-deployment.git $DEPLOY_DIR
            fi
            
            # --- Setup/Update Frontend Repo ---
            if [ -d "$FRONTEND_DIR" ]; then
              echo ">>> Actualizando repositorio del frontend..."
              cd $FRONTEND_DIR && git pull
            else
              echo ">>> Clonando repositorio del frontend..."
              git clone git@github.com:tu-usuario/instituto-asistencias-front.git $FRONTEND_DIR
            fi

            # --- Setup/Update Backend Repo ---
            if [ -d "$BACKEND_DIR" ]; then
              echo ">>> Actualizando repositorio del backend..."
              cd $BACKEND_DIR && git pull
            else
              echo ">>> Clonando repositorio del backend..."
              git clone git@github.com:tu-usuario/InstitutoAdv.API.git $BACKEND_DIR
            fi

            # --- Ejecutar el Despliegue ---
            echo ">>> Navegando al directorio de despliegue..."
            cd $DEPLOY_DIR
            
            echo ">>> Creando archivo .env..."
            echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
            
            echo ">>> Desplegando con Docker Compose..."
            docker compose up --build -d
            
            echo ">>> Limpiando imágenes de Docker no utilizadas..."
            docker image prune -f
            
            echo ">>> ¡Despliegue completado!"
